### ISSUE TITLE
Parachain Onboarding | NeuroWeb - 2043

### ISSUE THREAD

**Issue by al3mart** [paseo-network/support#102]
### Parachain Name

NeuroWeb

### ParaID

2043

### Parachain Manager Account

5D9kKJJXWuC6VPQFV7BDQVxGQM2tTzU9K4P5kDLmsCpJFnDD

### Upload your Genesis State - Do not submit a compressed file.

0x0

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

0x0

**Comment by Mihajlo-Pavlovic** [comment]
Runtime: 
[neuroweb_runtime_testnet_136.txt](https://github.com/user-attachments/files/17327552/neuroweb_runtime_testnet_136.txt)
