### ISSUE TITLE
ss58 missmatch in Paseo.

### ISSUE THREAD

**Issue by hbulgarini** [paseo-network/support#103]
Paseo is facing a ss58 missmatch between the runtime and the chain spec. 

More information:

https://github.com/paseo-network/runtimes/issues/135
https://github.com/paseo-network/runtimes/issues/137

**Comment by hbulgarini** [comment]
@pgolovkin @hitchhooker fix is being tested at the moment. If its works, we will deploy the fix across all the RPCs.

**Comment by hbulgarini** [comment]
@pgolovkin @hitchhooker, the fix has been deployed to the RPC located at:

`wss://paseo.rpc.amforc.com`

For the moment you can rely on this node until the rest of the nodes gets udpated as well.

**Comment by pgolovkin** [comment]
@hbulgarini it works. Thanks.
New metadata https://metadata.novasama.io/?tab=1#/paseo

**Comment by al3mart** [comment]
Closing this issue! 
Thanks @pgolovkin for the prompt action :)
