### ISSUE TITLE
[Parachain Onboarding | Slot Request]: ZetaGrid  ParaId: 4524

### ISSUE THREAD

**Issue by David-glitc** [paseo-network/support#105]
### Parachain Name

ZetaGrid

### ParaID

4524

### Parachain Manager Account

13Gy6ALawb6ceQT9TZpddbqukRJ94fJXyMdhU3Qn5dmQ4u72

### Upload your Genesis State - Do not submit a compressed file.

Https://crustipfs.xyz/ipfs/QmfV6Lvo1rBUA9FidnYvo6rgLToVpX6okZw6apxPjPgU8v?filename=para-4524-genesis-state

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

https://crustipfs.xyz/ipfs/QmZEgeEx77NHQzpUAzYdyPZgNp7W2gRstd3spCBCqE3dkF?filename=para-4524.wasm

**Comment by al3mart** [comment]
Hey @David-glitc, now you should be able to provision some coretime for your chain like explained in:
- https://wiki.polkadot.network/docs/learn-guides-coretime-parachains

But if you are finding any troubles on doing so, please feel free to drop a message here.

**Comment by David-glitc** [comment]
![image](https://github.com/user-attachments/assets/93cb43ec-d7fa-4b1e-b3e9-1aae4cf66acf)


I get this error when trying to run a collator node, any idea??
@al3mart

**Comment by al3mart** [comment]
Hey @David-glitc I don't know if you are following some old documentation, but `--parachain-id` is not something needed anymore.

I believe these guides should provide you with a better way of how to launch your nodes
- https://web3educhain.xyz/collator/
- https://paritytech.github.io/devops-guide/guides/parachain_deployment.html

**Comment by David-glitc** [comment]
Thanks

**Comment by David-glitc** [comment]
Shoot I have submitted a template not containing the updated keys for the chainspec used to create the genesis wasm build can I retract it

**Comment by al3mart** [comment]
Just update here the files that need to be registered and we can help pushing those

**Comment by David-glitc** [comment]
Runtime wasm: https://crustipfs.xyz/ipfs/QmZEgeEx77NHQzpUAzYdyPZgNp7W2gRstd3spCBCqE3dkF?filename=para-4524.wasm

Genesis State Wasm: https://gw.crustfiles.net/ipfs/QmeW6SNaxoB8BLABs7ou2mfS541hj9kcuxmm3LkW2vfMcz?filename=para-4524-genesis-state 

Parachain Manager and Sudo account: `5EFjffeNyeHjFLxkmVBHTQFstBepCgTGeadi2rdZDMe6krdV`

this would be all @al3mart, Ive also been able to get some coretime for the paraId and ive been able to get a node up just need to sync it all

**Comment by al3mart** [comment]
Hey @David-glitc would it be possible for you to attach the files directly to github ?
Thanks

**Comment by educlerici-zondax** [comment]
@David-glitc just a friendly reminder

**Comment by hbulgarini** [comment]
@David-glitc, is this request still needed? i'm afraid the files provided are not accessible. 
If not we will proceed to close this request and to take action when you are ready again.

**Comment by educlerici-zondax** [comment]
@David-glitc do we continue with this? or may we close this?

**Comment by hbulgarini** [comment]
Closing for now. Please let us know if you need any assitance.
