### ISSUE TITLE
[Parachain Onboarding | Slot Request]: Soft Law ParaId: 4528

### ISSUE THREAD

**Issue by ganesh1997oli** [paseo-network/support#107]
### Parachain Name

soft law

### ParaID

4528

### Parachain Manager Account

13mEPECpownFgBYbssfq23V8xjm2oarxieMVoKAKME4L8JXn

### Upload your Genesis State - Do not submit a compressed file.

[para-4528-genesis-state.txt](https://github.com/user-attachments/files/17469076/para-4528-genesis-state.txt)

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[para-4528-wasm.txt](https://github.com/user-attachments/files/17469077/para-4528-wasm.txt)

**Comment by wariomx** [comment]
gm

**Comment by al3mart** [comment]
![image](https://github.com/user-attachments/assets/eb375842-dc46-4810-afa6-b1bc7c4f6400)

The chain is now being registered

**Comment by al3mart** [comment]
Hey, can this issue be closed now or do you need any further assistance with your onboarding ?

**Comment by wariomx** [comment]
Yes, thanks for your help.
