### ISSUE TITLE
[Parachain Onboarding | Slot Request] ParaId: 4535 | Tangle Parachain

### ISSUE THREAD

**Issue by 1xstj** [paseo-network/support#109]
### Parachain Name

Tangle Parachain

### ParaID

4535

### Parachain Manager Account

13MUJccSrEbYJSDu17GAfWHf3Dki2fa7W2y1AbwDT3cv5LzU

### Upload your Genesis State - Do not submit a compressed file.

https://filetransfer.io/data-package/BdIRwqwM#link

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

https://filetransfer.io/data-package/BdIRwqwM#link

**Comment by al3mart** [comment]
@1xstj could you attach the files directly to github, pelase ? That would be very helpful.

Thanks!

**Comment by 1xstj** [comment]
[tangle-paseo.genesis.zip](https://github.com/user-attachments/files/17557896/tangle-paseo.genesis.zip)
[tangle-paseo.wasm.zip](https://github.com/user-attachments/files/17557897/tangle-paseo.wasm.zip)

done @al3mart

**Comment by 1xstj** [comment]
ping @al3mart

**Comment by al3mart** [comment]
![image](https://github.com/user-attachments/assets/38d6cf97-49d3-4595-9b40-346c8476a991)


Your chain is being registered now.

**Comment by al3mart** [comment]
Would you need any further assistance with coretime ?
You might most likely needs some funds from us if you want to do it yourselves

**Comment by 1xstj** [comment]
yes pls, could you pls assign a core so that we can create blocks

**Comment by al3mart** [comment]
The chain is assigned now
