### ISSUE TITLE
Document runtime upgrade process

### ISSUE THREAD

**Issue by hbulgarini** [paseo-network/support#11]

**Comment by educlerici-zondax** [comment]
I've created 4 docs for this process:

- doc_runtime_upgrade_communication_template.md: Communication template to be used for the Management team to communicate about the Runtime Upgrade Process.
- doc_runtime_upgrade_process.md: Document to explain about the hole Runtime Upgrade Process
- doc_runtime_upgrade_template.md: Template to use when a new Runtime Upgrade needs to be presented.
- doc_runtime_upgrade_validators_checklist.md: Checklist to use for validators after Runtime Upgrade.

TO-DO:
- Link documents between them
- Review technical concepts if they apply to Paseo process.
- Solve TO-DOs comments in markdown files.
