### ISSUE TITLE
[Parachain off-boarding] ParaId 4023

### ISSUE THREAD

**Issue by asiniscalchi** [paseo-network/support#112]
We kindly request assistance in downgrading the parachain with ID **4023** to a parathread. Additionally, we are prepared to deregister the parathread and withdraw the associated deposit.

## Context

- The network associated with parachain ID **4023** is bricked and non-functional.
- We plan to create a new parachain leveraging **coretime**.

## Request Details

1. **Downgrade:** Transition parachain 4023 to a parathread.

Thank you for your support in resolving this issue. Please let us know if any further steps are required from our side.

**Comment by educlerici-zondax** [comment]
related to what was asked in https://github.com/paseo-network/support/issues/86#issuecomment-2498030572

**Comment by hbulgarini** [comment]
Done.
