### ISSUE TITLE
[Parachain Onboarding | Parathread Request] ParaId: 4547

### ISSUE THREAD

**Issue by asiniscalchi** [paseo-network/support#113]
**WARNING: We just want a parathread, we'll use coretime to produce blocks**

### Parachain Name

Laos Venus

### ParaID

4547

### Parachain Manager Account

13ucKjHzhxsoXbqp4pshzXRYN4mjboNSiqwGLewPZXAioc7

### Upload your Genesis State - Do not submit a compressed file.

[laos-venus.state.txt](https://github.com/user-attachments/files/17905027/laos-venus.state.txt)

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[laos-venus.wasm.txt](https://github.com/user-attachments/files/17905033/laos-venus.wasm.txt)

**Comment by al3mart** [comment]
Onboarding parathread

**Comment by hbulgarini** [comment]
Parachain was onboarded and ready to use on demand.
