### ISSUE TITLE
Set monitoring for validators and system chain collators

### ISSUE THREAD

**Issue by hbulgarini** [paseo-network/support#15]

**Comment by hbulgarini** [comment]
As discussed in our internal call, we will start from a telemetry server to measure Uptime & Performance.

**Comment by educlerici-zondax** [comment]
as telemetry is already deployed and running in https://telemetry-paseo.beryx.io/#stats/0x77afd6190f1554ad45fd0d31aee62aacc33c6db0ea801129acb813f913e0764f
can we close this issue? cc @hbulgarini
