### ISSUE TITLE
[Parachain Onboarding] ParaId: 2015

### ISSUE THREAD

**Issue by brenzi** [paseo-network/support#31]
### Parachain Name

Integritee Network (Paseo)

### ParaID

2015

### Parachain Manager Account

5FNasVTkyjX1UsNrjs4mY1sGiiScf7BkFKzNZ2Cih9cXgfDy

### Upload your Genesis State - Do not submit a compressed file.

[integritee-paseo-1.9.4-dev2.zip](https://github.com/paseo-network/support/files/14692269/integritee-paseo-1.9.4-dev2.zip)

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[integritee_runtime-v50.compact.compressed.zip](https://github.com/paseo-network/support/files/14692273/integritee_runtime-v50.compact.compressed.zip)

**Comment by brenzi** [comment]
sorry, form only allowed upload of zip, not .wasm, not .state

**Comment by al3mart** [comment]
Parathread is now registering. 1h 30' to go.

**Comment by al3mart** [comment]
Slots have been assigned!

Your para should become a parachain soon. Please, use this issue for further support regarding this onboarding.
