### ISSUE TITLE
[Parachain Onboarding | Slot Request] ParaId: 4000 Frequency

### ISSUE THREAD

**Issue by wilwade** [paseo-network/support#32]
### Parachain Name

Frequency

### ParaID

4000

### Parachain Manager Account

5G4ADWnLUEWwDQ5mKQHEB9ASP7JrdXtUdo97RUpuxPeeKWtz

### Upload your Genesis State - Do not submit a compressed file.

0x000000000000000000000000000000000000000000000000000000000000000000805f6ddb6879aa31316a38c149e52ffe4e9f2a193e966ddcf3b6a2cb5846e96903170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c11131400

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

Renamed with .txt for the upload

[frequency-paseo.wasm.txt](https://github.com/paseo-network/support/files/14712844/frequency-paseo.wasm.txt)

**Comment by al3mart** [comment]
Parathread is being registered. 1h 30' to go from now.

**Comment by al3mart** [comment]
Slots have been assigned!

Your para should become a parachain soon. Please, use this issue for further support regarding this onboarding.
