### ISSUE TITLE
Migrate nodle paradis

### ISSUE THREAD

**Issue by simonsso** [paseo-network/support#36]
### Para Id in Rococo

2026

**Comment by simonsso** [comment]
I have not yet shut down out collators what changes to we need to do to our command line arguments when restarting them?

**Comment by simonsso** [comment]
What are the next steps now?
Do you need some more information or actions from our side?
or should we just agree on a suitable time to migrate?

**Comment by hbulgarini** [comment]
> What are the next steps now? Do you need some more information or actions from our side? or should we just agree on a suitable time to migrate?

Hello! Could you please provide us with your element handle ? We can coordinate the migration over there.

**Comment by simonsso** [comment]
> Hello! Could you please provide us with your element handle ? We can coordinate the migration over there.

```
 @nodle_fredrik:matrix.org
```

**Comment by simonsso** [comment]
> Hello! Could you please provide us with your element handle ? We can coordinate the migration over there.

Sent a PM there

**Comment by al3mart** [comment]
As per the discussion with @simonsso on DMs We are onboarding the following information:

paraId: `2026`
genesis head: `0x000000000000000000000000000000000000000000000000000000000000000000d756fab445775d52fb2df8b66ee4a13d717ddeb16dabd7106eebe31d27b68e8903170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c11131400`
manager_account: `5Chzw3acr3uEpxnX3Qc1sv96gB6AJir7duzaaz5xohXbZVkj`
genesis_wasm: 
[nodle-genesis-wasm.txt](https://github.com/paseo-network/support/files/14874226/nodle-genesis-wasm.txt)

**Comment by al3mart** [comment]
Slot assigned
