### ISSUE TITLE
[Parachain Onboarding | Slot Request] ParaId: 4001, Pop Network

### ISSUE THREAD

**Issue by peterwht** [paseo-network/support#39]
### Parachain Name

Pop Network

### ParaID

4001

### Parachain Manager Account

5CDhuAeazzmDxpEmJKAP1mxXYGg66XEMthz3XFqEANXGxHW8

### Upload your Genesis State - Do not submit a compressed file.

[pop-paseo-state.txt](https://github.com/paseo-network/support/files/14808524/pop-paseo-state.txt)

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[pop-paseo-wasm.txt](https://github.com/paseo-network/support/files/14808529/pop-paseo-wasm.txt)

**Comment by al3mart** [comment]
Parathread has been registered, ~1h 30' to go from now

**Comment by al3mart** [comment]
Parachain has been already onboarded and it's producing blocks!
