### ISSUE TITLE
[Parachain Onboarding | Slot Request] ParaId: 4006

### ISSUE THREAD

**Issue by asiniscalchi** [paseo-network/support#40]
### Parachain Name

LAOS Omega

### ParaID

4006

### Parachain Manager Account

5C7cTzUE8vhQMzbKrRmsZqhGgk583JFENE7T73faqUVeYMdC

### Upload your Genesis State - Do not submit a compressed file.

0x000000000000000000000000000000000000000000000000000000000000000000f60316e29864ed311108f2cb4499bdeb3156ad542ae3f48c72e351cd864108f403170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c11131400

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[laos-omega.genesis.wasm.txt](https://github.com/paseo-network/support/files/14872364/laos-omega.genesis.wasm.txt)

**Comment by al3mart** [comment]
Slot assigned, <2h for onboarding.
Please, feel free to use this issue for follow ups!

**Comment by asiniscalchi** [comment]
Hi there , we kindly request to reset LAOS Omega to the new Genesis state and validation Code

New state : 
[laos-omega.genesis.state.txt](https://github.com/paseo-network/support/files/14976027/laos-omega.genesis.state.txt)


New Validation code: 
[laos-omega.genesis.wasm.txt](https://github.com/paseo-network/support/files/14976033/laos-omega.genesis.wasm.txt)


Thanks

**Comment by al3mart** [comment]
New state and validation function submitted on chain.
