### ISSUE TITLE
Migration: Basilisk

### ISSUE THREAD

**Issue by green-jay** [paseo-network/support#41]
### Para Id in Rococo
2090

### Chainspec
[basilisk-paseo.json](https://github.com/paseo-network/support/files/15132721/basilisk-paseo.json)

### State
[basilisk-state.txt](https://github.com/paseo-network/support/files/15132722/basilisk-state.txt)

### Wasm
[basilisk-wasm.txt](https://github.com/paseo-network/support/files/15132728/basilisk-wasm.txt)

### Parachain block
2852081

### Parachain Manager Account

Same as on Rococo

**Comment by al3mart** [comment]
Parathread being onboarded right now

**Comment by hbulgarini** [comment]
Hello @green-jay ! we see the parachain onboarded but not producing blocks, are the collators up and running? In case they are, do you notice any error in the logs?

**Comment by hbulgarini** [comment]
@green-jay FYI: After some internal discussions we decided to allow Basilisk parachain temporary until the demand for cores increases. We didn't officialized yet, but the rule will be one core per parachain team in Paseo.

**Comment by green-jay** [comment]
> @green-jay FYI: After some internal discussions we decided to allow Basilisk parachain temporary until the demand for cores increases. We didn't officialized yet, but the rule will be one core per parachain team in Paseo.

Hi @hbulgarini, ty for making the exception. It makes sense for the canary model. But Basilisk is not the case, it is a separate parachain project with a partially different feature set and partially different group of people working on it compared to Hydra.

Collator onboarding is in the pipeline, I'll keep you updated.

**Comment by green-jay** [comment]
> hello @green-jay ! i saw that hydradx is producing blocks already in Paseo, i was wondering if the collators were already onboarded for this one and the block production is not working.

hi, yes our collator is producing:
`[Parachain] Could not find the header of the genesis block in the database! block_hash=0x4d76327abf28e4823370821763e45fbac5525fbab30a79b0f32112ef7d607938`
looks like the genesis block mismatch

**Comment by educlerici-zondax** [comment]
hey @green-jay Just saw your last update about the genesis block mismatch – sounds like a tricky one! Have you managed to resolve that, or is there anything specific you're trying right now to sort it out? Keen to hear how it's going and if there’s any way I can help!

**Comment by educlerici-zondax** [comment]
@green-jay any update regarding this one?

**Comment by educlerici-zondax** [comment]
We will close this issue for now but will reopen it if there are new updates or submissions. Please feel free to add any further comments or concerns.

**Comment by mrq1911** [comment]
please give some slot to basilisk, so we can debug it

**Comment by al3mart** [comment]
![image](https://github.com/paseo-network/support/assets/11448715/efbb82b6-b3d8-4549-bf03-205c490460b9)

Basilisk has been slotted :handshake:

**Comment by hbulgarini** [comment]
@mrq1911 How is your debugging going? Any estimation for making the parachain to produce blocks?

**Comment by educlerici-zondax** [comment]
@mrq1911 any update? 🙏

**Comment by hbulgarini** [comment]
Hello @mrq1911 @green-jay, the next week we will be doing a cleanup on Paseo for parachains not producing blocks. This is the last chance in case you want to debug the parachain or otherwise we will have to offboard it.

Thanks.

**Comment by green-jay** [comment]
Testing purposes only:

State:
[cleanspec.state.txt](https://github.com/user-attachments/files/17585323/cleanspec.state.txt)

Wasm:
[cleanspec.wasm.txt](https://github.com/user-attachments/files/17585326/cleanspec.wasm.txt)

**Comment by green-jay** [comment]
Another try:
[basilisk-mainnet-paseo-3.state.txt](https://github.com/user-attachments/files/17590106/basilisk-mainnet-paseo-3.state.txt)
[basilisk-mainnet-paseo-3.wasm.txt](https://github.com/user-attachments/files/17590107/basilisk-mainnet-paseo-3.wasm.txt)
