### ISSUE TITLE
Migration: HydraDX

### ISSUE THREAD

**Issue by green-jay** [paseo-network/support#42]
### Para Id in Rococo

2034

### Chainspec
[hydradx-paseo.json](https://github.com/paseo-network/support/files/15132578/hydradx-paseo.json)

### State
[hydradx-state.txt](https://github.com/paseo-network/support/files/15132580/hydradx-state.txt)

### Wasm
[hydradx-wasm.txt](https://github.com/paseo-network/support/files/15132581/hydradx-wasm.txt)

### Parachain block
2238026

### Parachain Manager Account

Same as on Rococo

**Comment by green-jay** [comment]
> We are doing a refactor to the migration guide so we can streamline these a bit better.
> 
> Bear with us, will share it here soon so we can start moving ahead with your migration for both, Hydra and Basilisk.

Can you please share some timeline wrt the paseo migration? we'd like to also test the KSM-DOT bridge and rococo is the only place where to do it afaik, so maybe we should wait a bit with the migration?

**Comment by al3mart** [comment]
Hi!

We are targeting to deploy bridge hub after the enactment of the coming runtime. We can move ahead migrating your parachains from Rococo to Paseo as it best fit based on that. Just let me know and we can start preparing things accordingly.

For the moment we have pushed a few changes to the migration guidelines here - https://github.com/paseo-network/support/pull/47

**Comment by green-jay** [comment]
> Hi!
> 
> We are targeting to deploy bridge hub after the enactment of the coming runtime. We can move ahead migrating your parachains from Rococo to Paseo as it best fit based on that. Just let me know and we can start preparing things accordingly.
> 
> For the moment we have pushed a few changes to the migration guidelines here - #47

Thanks, I have updated the issue description according to the manual.

**Comment by al3mart** [comment]
Parathread onboarding now

**Comment by hbulgarini** [comment]
> > Hi!
> > We are targeting to deploy bridge hub after the enactment of the coming runtime. We can move ahead migrating your parachains from Rococo to Paseo as it best fit based on that. Just let me know and we can start preparing things accordingly.
> > For the moment we have pushed a few changes to the migration guidelines here - #47
> 
> Thanks, I have updated the issue description according to the manual.

Hello @green-jay, any news about the collators deployment? Is in our interest that parachains asking for a Paseo slot, keep the infrastructure up and running otherwise the slot is being wasted. For the records we have a clean-up process to be activated where parachains stalled for more than two weeks are removed.

Could you please go ahead and deploy the collators this week and make the parachain active to keep the slots?

**Comment by green-jay** [comment]
Mainnet regenesis:
[hydration-mainnet-paseo.state.txt](https://github.com/user-attachments/files/17494541/hydration-mainnet-paseo.state.txt)
[hydration-mainnet-paseo.wasm.txt](https://github.com/user-attachments/files/17494542/hydration-mainnet-paseo.wasm.txt)
