### ISSUE TITLE
Request to migrate parachain 2105 from Rococo to Paseo.

### ISSUE THREAD

**Issue by AurevoirXavier** [paseo-network/support#43]
### Para Id in Rococo

2105

**Comment by AurevoirXavier** [comment]
I can't find the manager account I think it might relate to https://github.com/paritytech/subport/issues/341.

**Comment by al3mart** [comment]
No worries, an account you control on paseo should be enough.
We are doing a refactor to the migration guide so we can streamline these a bit better.

Bear with us, will share it here soon so we can start moving ahread with your migration.

**Comment by al3mart** [comment]
Hello @AurevoirXavier! In preparation for the migration could you check this guidelines and get some of the requested information ready ?

- https://github.com/paseo-network/support/blob/main/docs/rococo_migration.md

Thanks

**Comment by AurevoirXavier** [comment]
> Hello @AurevoirXavier! In preparation for the migration could you check this guidelines and get some of the requested information ready ?

Okay, I'll check this ASAP.

**Comment by AurevoirXavier** [comment]
BTW, does Paseo supports async backing? @al3mart

**Comment by al3mart** [comment]
It does :)

**Comment by hbulgarini** [comment]
Hey @AurevoirXavier ! what is the status of this request? would you like to proceed with the parachain onboarding? You should provide the genesys code and head.

**Comment by AurevoirXavier** [comment]
> Hey @AurevoirXavier ! what is the status of this request? would you like to proceed with the parachain onboarding? You should provide the genesys code and head.

We are undergoing a runtime upgrade and using the testnet for testing. I think we can proceed this 2 days later.

**Comment by al3mart** [comment]
How is this looking @AurevoirXavier  ? There's no rush from our side, we can easily adapt to your timeline.

**Comment by AurevoirXavier** [comment]
> How is this looking @AurevoirXavier ? There's no rush from our side, we can easily adapt to your timeline.

I'll do this afternoon.

**Comment by AurevoirXavier** [comment]
After some discussion, our team decided to start a new chain. However, please retain paraid 2105 for us.
