### ISSUE TITLE
Request to migrate Curio parachain from Rococo to Paseo

### ISSUE THREAD

**Issue by alexxxkny** [paseo-network/support#51]
### ParaId
3339
### Migrating from block#
Parachain block: 600000
Rococo block: 10137697
### Manager account
5FFaHNwYDhY5DUBazJqA16Ck1iFY9CmSnXc1r7yDsrjRBLx8
### Proof of ownership
"PASEO" signed with 5FFaHNwYDhY5DUBazJqA16Ck1iFY9CmSnXc1r7yDsrjRBLx8:
0x944e784c811df917ba54a581d1dbdd347b97ec030ca1ad9056340a1a72c9101ebfb2a1c7588c9c9c102158d3415f0e26f2a15e2e096e78577a01985fc6896880
### Genesis head and wasm
[genesis-wasm.txt](https://github.com/paseo-network/support/files/15076832/genesis-wasm.txt)
[genesis-head.txt](https://github.com/paseo-network/support/files/15076833/genesis-head.txt)

**Comment by alexxxkny** [comment]
Greetings Paseo team! Could you please elaborate a little on the timelines of requested parachain migrations?

**Comment by al3mart** [comment]
Hey @alexxxkny ,

as a preparation for your migration, could you check if your state includes a value for the key `0x45323df7cc47150b3930e2666b0aa313a2bca190d36bd834cc73a38fc213ecbd` ?

This could be easily inspected in the spec that you have exported the genesis wasm and state from :+1: 

If that is the case, please, let me know and I'll assist addressing it. I am sorry that the current guidelines for the migration doesn't cover this.

The mentioned key corresponds to the last relay block observed by the parachain, which if migration from Rococo, would be way bigger than whatever relay block Paseo might have produced so far, what will derive in the parachain runtime erring.

**Comment by alexxxkny** [comment]
@al3mart, @hbulgarini Hi! Sorry for the long reply. I was a little hasty with submitting a request. As Alejandro mentioned we firstly have to prepare migrated genesis to make some things work from the 1st block again. But we don't actually have a reason to migrate state from Rococo so I will just open an onboarding request later when launching Paseo will be relevant for us again. So this issue can be closed so far
