### ISSUE TITLE
Integrate RPC endpoints into Polkadot.js

### ISSUE THREAD

**Issue by educlerici-zondax** [paseo-network/support#52]
**Description**:
As part of our ongoing efforts to enhance accessibility and connectivity for our users, we need to integrate two RPC endpoints from Stakeworld.io into the Polkadot.js interface. These endpoints are critical for providing our community with reliable access to the Paseo testnet and its associated AssetHub

**Endpoints to be Integrated:**
* wss://pas-rpc.stakeworld.io - Main Paseo testnet RPC endpoint.
* wss://pas-rpc.stakeworld.io/assethub - Dedicated endpoint for AssetHub functionalities.

**Comment by hbulgarini** [comment]
https://github.com/polkadot-js/apps/pull/10530
