### ISSUE TITLE
[Parachain Onboarding | Slot Request] ParaId: 2119

### ISSUE THREAD

**Issue by clangenb** [paseo-network/support#56]
Hey there, we would like to onboard our bajun parachain to Paseo. We don't need to migrate an old one, we'd like to start fresh!

Genesis state and wasm have been taken from here: https://github.com/ajuna-network/bajun-parachain/tree/develop/resources/bajun/paseo

### Parachain Name

Bajun Paseo

### ParaID

2119

### Parachain Manager Account

5Hgh334723ay3Zt34woP3wqY9RwFs9556QvY4UWqFTKvy91f

### Upload your Genesis State - Do not submit a compressed file.

[bajun-paseo-state.txt](https://github.com/paseo-network/support/files/15221920/bajun-paseo-state.txt)

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[bajun-paseo-wasm.txt](https://github.com/paseo-network/support/files/15221923/bajun-paseo-wasm.txt)

**Comment by hbulgarini** [comment]
Parachain is onboarding.

**Comment by hbulgarini** [comment]
@clangenb the parachain was onboarded successfully however is not producing blocks. Are the collators up and running?

**Comment by clangenb** [comment]
We are now producing blocks as stated in #58 👍

**Comment by educlerici-zondax** [comment]
@clangenb it seems that your parachain is not producing blocks, can you please restart your collators when possible? thanks
