### ISSUE TITLE
FEAT - Implement StableCoins and Other Assets in AssetHub

### ISSUE THREAD

**Issue by educlerici-zondax** [paseo-network/support#64]
**Is your feature request related to a problem? Please describe.**

Currently, the Paseo Testnet's AssetHub needs some financial instruments, particularly StableCoins. This, to test financial applications under realistic conditions, which could lead to less robust dApps being developed on the network.

**Describe the solution you'd like**
We propose the introduction of StableCoins and a variety of other interesting assets within the Paseo Testnet's AssetHub. This implementation should include:

* Development and deployment of various types of StableCoins that mirror real-world financial assets.
* Integration of other significant assets to broaden the scope of testing and development on the network.
* Comprehensive documentation and guidelines on how to utilize these assets within the network.

**Describe alternatives you've considered**
An alternative would be to partner with existing blockchain projects that specialize in asset management and integration to leverage their technologies within Paseo. However, directly implementing these assets on the AssetHub will provide tighter integration and better control over the assets' behavior and interaction with the network.

**Additional context**
Adding these assets is crucial for simulating real-world economic activities and providing developers with the necessary tools to test the economic models of their applications thoroughly. This move will also potentially increase network engagement by attracting developers who are interested in building financial applications.

**Comment by hbulgarini** [comment]
USDC & USDT deployed on AH.
