### ISSUE TITLE
[Parachain Onboarding | Slot Request] ParaId: 2051

### ISSUE THREAD

**Issue by clangenb** [paseo-network/support#68]
### Parachain Name

Ajuna Paseo

### ParaID

2051

### Parachain Manager Account

5Hgh334723ay3Zt34woP3wqY9RwFs9556QvY4UWqFTKvy91f

### Upload your Genesis State - Do not submit a compressed file.

[ajuna-paseo.state.txt](https://github.com/user-attachments/files/15551725/ajuna-paseo.state.txt)

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[ajuna-paseo.wasm.txt](https://github.com/user-attachments/files/15551726/ajuna-paseo.wasm.txt)

**Comment by clangenb** [comment]
We have recently onboarded Paseo with Bajun which is our Kusama parachain, but as our Kusama and Polkadot parachain runtimes are not identical in terms of Business Logic, we would like to ask for another slot that we can use with our Polkadot Parachain Ajuna.

In my opinion, this is reasonable, as we probably want to have many parachains on Paseo anyhow to see how the relay chain is able to handle that. :)

**Comment by al3mart** [comment]
It should be OK for now.
Though, I'd like to be clear that once we need to optimize the resources we will need to prioritize Polkadot parachains.

**Comment by clangenb** [comment]
> It should be OK for now. Though, I'd like to be clear that once we need to optimize the resources we will need to prioritize Polkadot parachains.

Alright, thanks a lot! I totally understand that!

Thanks for the quick action.

**Comment by clangenb** [comment]
Deployed collators and producing blocks now 👍
