### ISSUE TITLE
[QUESTION] - Temporary slot for parachain testing in paseo

### ISSUE THREAD

**Issue by Mrigesh901** [paseo-network/support#69]
### Question Overview

How to get temporary slot for parachain testing in paseo

### Detailed Description

If someone is trying out paseo testnet for the first time and they are using parachain node template as parachain runtime and paseo as relay chain just for the purpose of testing, should they open an issue in github for slot request or is there any other way to do this?

### What You Have Tried

I have already compiled parachain-node-template, generated genesis and genesis-wasm, synced the relay chain and started the parachain node.

### Expected Outcome

Parathread gets a slot and become parachain, blocks get generated and finalized for parachain.

# Other information
ParaID - 4003

**Comment by hbulgarini** [comment]
hello @Mrigesh901 ! we are happy to give you a temporary slot in Paseo to test your parachain. Could you please provide the genesis code and the head state for being able to register the parachain?

This doc might help: https://docs.substrate.io/tutorials/build-a-parachain/connect-a-local-parachain/

Also adding @sacha-l in the loop who is our devrel champion in the ecosystem :)

**Comment by Mrigesh901** [comment]
Genesis-state file:
[genesis-state.txt](https://github.com/user-attachments/files/15604861/genesis-state.txt)
Wasm file:
[wasm.txt](https://github.com/user-attachments/files/15604870/wasm.txt)

**Comment by al3mart** [comment]
Hey @Mrigesh901 sorry for the late action here.

Your chain will be onboarded soon.
![image](https://github.com/paseo-network/support/assets/11448715/a124d5ea-5c06-42eb-b7c8-325027b200af)

**Comment by al3mart** [comment]
I have removed the manager lock from your para so you are free to modify the registered genesis state and wasm with your manager account.

I'm closing this for now as no further action is needed in regards to the onboarding. But feel free to keep on commenting in this issue if something else pops up.

**Comment by Mrigesh901** [comment]
Parachain is not producing blocks.
 [Parachain] 💤 Idle (0 peers), best: #0 (0x7601…207e), finalized #0 (0x7601…207e), ⬇ 18 B/s ⬆ 54 B/
How to start producing blocks?
Can you help me out?

**Comment by hbulgarini** [comment]
> Parachain is not producing blocks. [Parachain] 💤 Idle (0 peers), best: #0 (0x7601…207e), finalized #0 (0x7601…207e), ⬇ 18 B/s ⬆ 54 B/ How to start producing blocks? Can you help me out?

Hey @Mrigesh901!

If you share the logs of your collator, we could try taking a look. I assume that you have a collator deployed that is running all the time correct? Otherwise, i would recommend using https://github.com/r0gue-io/pop-cli to launch a local testnet. 

Nevertheless, is out of our scope to debug parachains and why blocks are not being produced. From our side, we do everything that is necessary from the relay chain POV to assure parachains can join. 

There are on-going efforts from different devrel teams to deliver an updated documentation for paracain deployment. I saw this presentation from Rahda that can point out the needed steps to spin the collator:

https://docs.google.com/presentation/d/1OAZtIFkzy1AVI0acx1r-EoynqLPUuuhu/edit?usp=drivesdk&ouid=100312476344501614015&rtpof=true&sd=true

**Comment by al3mart** [comment]
Sure, you need to check that the keys that are set as the initial collators in your chain's spec are the ones your nodes are running with.

Other than that I don't know what can be happening, so maybe share have a look at the logs of your parachain and see if there's any pointers there. Feel free to paste them here, or in a https://substrate.stackexchange.com post to receive guidance on understanding them.

A flag that might be interesting to receive extra information on your logs is `-ldebug=basic-authorishop`.

As @hbulgarini points out, it might be that the genesis wasm and state registered in the relay doesn't match what your are running at the moment, the best way to double check would be re generating them again and comparing if the registered information is correct.

**Comment by educlerici-zondax** [comment]
@Mrigesh901 just a friendly reminder to check if that help does works for you?

**Comment by hbulgarini** [comment]
@Mrigesh901 are you planning to start the collator? otherwise by Friday we would need to unregister the parachain to leave the slot available.

**Comment by Mrigesh901** [comment]
@hbulgarini In the chainspec file that i provided you, i did not set any keys to  it. Maybe that's why blocks are not being produced. 
Can you tell , if something can be done on this existing scenario? . If not, we can deregister the parachain on friday.

**Comment by hbulgarini** [comment]
> https://docs.google.com/presentation/d/1OAZtIFkzy1AVI0acx1r-EoynqLPUuuhu/edit?usp=drivesdk&ouid=100312476344501614015&rtpof=true&sd=true

in that case you might want to try starting the collators with the dev profiles --alice or --bob , however this is not a good practice at all but for the testing sake it would work. 

There is one devrel team that is already writting the documentation for onboarding correctly a parachain and i hope that will clarify all the doubts. 

What about if one the doc is out, you try the whole process again? We would be very happy to assist you following the doc.

**Comment by Mrigesh901** [comment]
Yes please, that would be great.

**Comment by hbulgarini** [comment]
@Mrigesh901 we are closing this for now. As soon as the doc is ready we will let you know so you can re onboard your parachain.
