### ISSUE TITLE
Organize Github permissions and branch rules protection

### ISSUE THREAD

**Issue by hbulgarini** [paseo-network/support#7]

**Comment by carlosala** [comment]
I already added branch protection for all three repos (support, runtimes, rfcs). It needs PR + 1 approval. We can tweak this in the future 👍🏻 
Regarding Github Teams, I propose to create one Github Team per team working on Paseo (we can assign permissions to the repos to the whole team, from `read` to `admin`) and restrict to just one org owner per team.
Only org owners are allowed to bypass branch protection rules.
What do you think @educlerici-zondax @hbulgarini @al3mart?

**Comment by hbulgarini** [comment]
> I already added branch protection for all three repos (support, runtimes, rfcs). It needs PR + 1 approval. We can tweak this in the future 👍🏻 Regarding Github Teams, I propose to create one Github Team per team working on Paseo (we can assign permissions to the repos to the whole team, from `read` to `admin`) and restrict to just one org owner per team. Only org owners are allowed to bypass branch protection rules. What do you think [@educlerici-zondax](https://github.com/educlerici-zondax) [@hbulgarini](https://github.com/hbulgarini) [@al3mart](https://github.com/al3mart)?

Thanks! let's add as owners @lovelaced and @helloitsbirdo from parity as well (it would be an exception to the one member per organization, but that is fine i think)

**Comment by hbulgarini** [comment]
@carlosala is there anything missing or we can close this?

**Comment by carlosala** [comment]
I'd say it's fully done!
