### ISSUE TITLE
[Parachain Onboarding | Slot Request] ParaId: 3344

### ISSUE THREAD

**Issue by JuaniRios** [paseo-network/support#70]
### Parachain Name

Polimec

### ParaID

3344

### Parachain Manager Account

5GGgn2FDUAKgws38oCNFNC9gC8d5mqRgHRAnWaNSQVkyweo6

### Upload your Genesis State - Do not submit a compressed file.

https://raw.githubusercontent.com/Polimec/polimec-node/main/chain-specs/paseo/polimec-paseo.genesis.state

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

https://raw.githubusercontent.com/Polimec/polimec-node/main/chain-specs/paseo/polimec-paseo.genesis.wasm

**Comment by al3mart** [comment]
![image](https://github.com/paseo-network/support/assets/11448715/b2d6de11-eeea-457c-8ef1-a982341ab4f0)

Onboarding starting
