### ISSUE TITLE
[QUESTION] - Replacing our genesis WASM and State. Para 3344

### ISSUE THREAD

**Issue by JuaniRios** [paseo-network/support#73]
### Question Overview

We compiled the wrong runtime wasm/state, so we need a force replacement. 

### Detailed Description

We talked in our internal channel with the Paseo team and they agreed to replace the wasm and state with the correct one we supplied. This has been done already, so this issue is more for documentation purposes.

**Comment by hbulgarini** [comment]
wasm and state were provided privately and were pushed as requested.
