### ISSUE TITLE
[QUESTION] - Request opening HRMP channel with AssetHub

### ISSUE THREAD

**Issue by AurevoirXavier** [paseo-network/support#75]
Request opening the HRMP channels between 2105 and AssetHub.

And please set the asset 7777's sufficient to `true`. That you have done this in the Rococo before. So, we can use it to pay the fee.

**Comment by hbulgarini** [comment]
Hey @AurevoirXavier ! I'm sorry for the late action on this one, we are currently dealing with a limitation exceed issue when opening the channel that i need to take a look why is that happening. 

However is see the 2105 parachain down. Could you please check it ?

**Comment by acgxv** [comment]
> However is see the 2105 parachain down. Could you please check it ?

Looks good on my side.

<img width="883" alt="image" src="https://github.com/paseo-network/support/assets/16152305/602d0632-8e2a-4819-bd19-ce9136279bb0">

**Comment by hbulgarini** [comment]
strange... when i sent the message the parachains seemed stalled. Maybe the it was something with RPC... i see all good from my side as well.

Good news is that i managed to open the HRMP channel and also the asset ID 7777 was set as sufficient as requested.

In case something is not working as expected please feel free to re open the issue.

**Comment by acgxv** [comment]
> strange... when i sent the message the parachains seemed stalled. Maybe the it was something with RPC... i see all good from my side as well.

We use a load balancer. I believe some of the nodes are slow at that point.
