### ISSUE TITLE
[Parachain Onboarding | Slot Request] Kreivo de Paseo - ParaId: 2281

### ISSUE THREAD

**Issue by pandres95** [paseo-network/support#77]
### Parachain Name

Kreivo de Paseo

### ParaID

2281

### Parachain Manager Account

EvoLanodoqDsgHb98Ymbu41uXXKfCPDKxeM6dXHyJ2JoVus

### Upload your Genesis State - Do not submit a compressed file.

[kreivo-head.bin.txt](https://github.com/user-attachments/files/16175418/kreivo-head.bin.txt)

Note: remove the `.txt` trailing extension (appended it so it was accepted by GitHub)

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[kreivo-local-paseo.wasm.txt](https://github.com/user-attachments/files/16175420/kreivo-local-paseo.wasm.txt)

Note: remove the `.txt` trailing extension (appended it so it was accepted by GitHub)

**Comment by hbulgarini** [comment]
As i shared in DM, the parachain was onboarded but the collator does not seem to produce blocks.

**Comment by hbulgarini** [comment]
Parachain is up and running.

**Comment by al3mart** [comment]
Hey @pandres95, it seems that your para hasn't been producing blocks lately.
In case you missed it, after enacting coretime a restart of the collators was required.

Please let me know if the slot is still something useful for your team!
