### ISSUE TITLE
[Parachain Onboarding | Slot Request] ParaId: 4022

### ISSUE THREAD

**Issue by zianksm** [paseo-network/support#79]
### Parachain Name

Niskala

### ParaID

4022

### Parachain Manager Account

5GbvVtuHvN1PG9WdG4FXKCPzVnPtUKRQMEy3Aye1VYEYsKB3

### Upload your Genesis State - Do not submit a compressed file.

[niskala-genesis-state.txt](https://github.com/user-attachments/files/16229349/genesis-state.txt)

Note: remove the .txt file extension

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[niskala-genesis-wasm.wasm.txt](https://github.com/user-attachments/files/16229357/genesis-wasm.wasm.txt)
Note: remove the .txt file extension

### Polkadot JS PR 
https://github.com/polkadot-js/apps/pull/10760

**Comment by zianksm** [comment]
Hi! is there a time estimation on when will this be completed?

**Comment by hbulgarini** [comment]
![Screenshot 2024-07-17 at 10 11 26](https://github.com/user-attachments/assets/e6874bd1-875c-41d7-8d79-07daa302bccf)

Parachain is being onboarded. Please make sure your collators are up and running.

**Comment by agustinustheo** [comment]
Hi @hbulgarini the Niskala Testnet is not running at the moment.

**Comment by al3mart** [comment]
@agustinustheo thanks for the answer! Are you guys planning on running the collators any time soon ?
Would be great for us to know in order to do a better management of the resources of the network.
Thanks!

**Comment by hbulgarini** [comment]
> Hi @hbulgarini the Niskala Testnet is not running at the moment.

@agustinustheo we try to avoid working on closed issues as this makes our daily management harder.

As i shared in our private conversation, the parachain is well configured and it's included in the workplan. In case a restart is required, please request it in a new issue and we will take action.
