### ISSUE TITLE
[Parachain Onboarding | Slot Request] AVN_Paseo - ParaId: 2056

### ISSUE THREAD

**Issue by ivan-cholakov** [paseo-network/support#80]
### Parachain Name

avn_paseo

### ParaID

2056

### Parachain Manager Account

5EAMoEXiv7ceKPTFQLRNjMxj268LN32J7EQt3AV1R5sfXx6L

### Upload your Genesis State - Do not submit a compressed file.

[genesis-state.txt](https://github.com/user-attachments/files/16233661/genesis-state.txt)

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[genesis-wasm.txt](https://github.com/user-attachments/files/16233670/genesis-wasm.txt)

**Comment by al3mart** [comment]
![image](https://github.com/user-attachments/assets/47f9bd04-5081-4f9a-9794-459f60d6938d)

Your chain is being onboarded as a parathread right now. Slot assignment will follow.

**Comment by al3mart** [comment]
Leases has been assigned, the parachain is upgrading right now.

**Comment by ivan-cholakov** [comment]
Hey @al3mart , really apreaciate it. Would it be possible to reset the chain with our new wasm and state files? Attaching them for convenience.
[paseo_v2_genesis.state.txt](https://github.com/user-attachments/files/16346328/paseo_v2_genesis.state.txt)
[paseo_v2_genesis.wasm.txt](https://github.com/user-attachments/files/16346329/paseo_v2_genesis.wasm.txt)

**Comment by al3mart** [comment]
We have removed the manager lock so that you guys can change those anytime as per your needs with
```
registrar.setCurrentHead
registrar.scheduleCodeUpgrade
```

**Comment by ivan-cholakov** [comment]
Great, thanks a lot!

**Comment by nahuseyoum** [comment]
Hi @al3mart @educlerici-zondax thank you for the advice. We tried resetting the state and schedule a code upgrade ([please see here](https://paseo.subscan.io/account/5EAMoEXiv7ceKPTFQLRNjMxj268LN32J7EQt3AV1R5sfXx6L)) but the new wasm code is not applied and our chain is not able to produce blocks. We can still see an entry in `paras.futureCodeUpgrades` for our parachain even though the block has passed. Is there something we are doing wrong? How can we get Paseo to accept our new wasm?

**Comment by al3mart** [comment]
This was sorted and the chain is now producing blocks
