### ISSUE TITLE
[Parachain Onboarding | Slot Request] ParaId: 3369

### ISSUE THREAD

**Issue by moliholy** [paseo-network/support#82]
### Parachain Name

Muse

### ParaID

3369

### Parachain Manager Account

5CK5QCWE5DkiCZ2ufodegLFV795vPdMJMHbncMyv6qd4BKbH

### Upload your Genesis State - Do not submit a compressed file.

[genesis-state.txt](https://github.com/user-attachments/files/16248675/genesis-state.txt)

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[genesis-wasm.txt](https://github.com/user-attachments/files/16248677/genesis-wasm.txt)

**Comment by al3mart** [comment]
![image](https://github.com/user-attachments/assets/4dc060ad-3f03-45b2-ba80-860be6f2ad88)

Slot assignment will come after parathread onboarding

**Comment by al3mart** [comment]
Collators are producing blocks as expected
