### ISSUE TITLE
[Parachain Onboarding | Slot Request] PhalaPaseo - ParaId: <2004>

### ISSUE THREAD

**Issue by tolak** [paseo-network/support#83]
### Parachain Name

PhalaPaseo

### ParaID

2004

### Parachain Manager Account

5FNUsoMKdSFpPs7dcgzgqtRmoH2zDbs9eqwAMKLNWD2LkLjc

### Upload your Genesis State - Do not submit a compressed file.

https://github.com/tolak/parachain-res/blob/main/rhala/2023-11-08/rhala-staging-state.hex

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

https://github.com/tolak/parachain-res/blob/main/rhala/2023-11-08/rhala-staging-code.wasm

**Comment by al3mart** [comment]
![image](https://github.com/user-attachments/assets/ff6a0e95-dacd-4ec5-8cb2-e9c19944750e)

Onboarding parathread, slot assignment following after this is done

**Comment by al3mart** [comment]
It seems that your nodes are not yet running, or your collators are having some troubles to start block production. Please, let us know if you need further assistance or action from our side.

**Comment by tolak** [comment]
@al3mart Yeah, our node is done, will get back to you when we solve it

**Comment by tolak** [comment]
I'm gonna close the issue since we decided pause the parachain registration on Paseo, will reopen when we needed

**Comment by al3mart** [comment]
Hey @tolak just a heads up that the parachain is not producing blocks atm.
In case you missed it after enacting coretime a restart of the collators was needed.
