### ISSUE TITLE
[Xcavate Parachain Onboarding | Slot Request] ParaId: 4003

### ISSUE THREAD

**Issue by ganesh1997oli** [paseo-network/support#84]
### Parachain Name

xcavate

### ParaID

4003

### Parachain Manager Account

5CwhKMkBwxSwHb9ckhTPPwJeSPEM2vAP5fc1rj5ZGx6k1xyi

### Upload your Genesis State - Do not submit a compressed file.

[dip-xcavate-para-4003-genesis-state.txt](https://github.com/user-attachments/files/16331520/dip-xcavate-para-4003-genesis-state.txt)

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[dip-xcavate-para-4003-wasm.txt](https://github.com/user-attachments/files/16331523/dip-xcavate-para-4003-wasm.txt)

**Comment by hbulgarini** [comment]
@ganesh1997oli could you please confirm in advance that collators are running and synced already?

**Comment by ganesh1997oli** [comment]
> @ganesh1997oli could you please confirm in advance that collators are running and synced already?

hey @hbulgarini I have some issue can I update you later?
