### ISSUE TITLE
[Xcavate Parachain Onboarding | Slot Request] ParaId: 4003

### ISSUE THREAD

**Issue by ganesh1997oli** [paseo-network/support#85]
### Parachain Name

xcavate

### ParaID

4003

### Parachain Manager Account

5CwhKMkBwxSwHb9ckhTPPwJeSPEM2vAP5fc1rj5ZGx6k1xyi

### Upload your Genesis State - Do not submit a compressed file.

[para-4105-genesis-state.txt](https://github.com/user-attachments/files/16336854/para-4105-genesis-state.txt)

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[para-4003-wasm.txt](https://github.com/user-attachments/files/16336855/para-4003-wasm.txt)

**Comment by ganesh1997oli** [comment]
hey @hbulgarini, collators are running and synced already. Can you please onboard?

**Comment by hbulgarini** [comment]
i need one more check from your side:

the title for the para state says 4105, and the para ID requested is 4003. Could you please confirm that the miss match with the 4105 and confirm that all your para id values are set to 4003? Otherwise the parachain will not produce blocks.

**Comment by ganesh1997oli** [comment]
> i need one more check from your side:
> 
> the title for the para state says 4105, and the para ID requested is 4003. Could you please confirm that the miss match with the 4105 and confirm that all your para id values are set to 4003? Otherwise the parachain will not produce blocks.

actually, I forgot to modify the name of file as 4003 from 4104 while generating genesis state.  Here are the files:

[para-4003-genesis-state.txt](https://github.com/user-attachments/files/16358855/para-4003-genesis-state.txt)
[para-4003-wasm.txt](https://github.com/user-attachments/files/16358856/para-4003-wasm.txt)

**Comment by hbulgarini** [comment]
It seems the wasm file is not the compressed version and the RPCs are rejecting the call due to the file's size. Please provide the compressed wasm version.

**Comment by ganesh1997oli** [comment]
> It seems the wasm file is not the compressed version and the RPCs are rejecting the call due to the file's size. Please provide the compressed wasm version.

sure

**Comment by hbulgarini** [comment]
<img width="702" alt="Screenshot 2024-07-24 at 13 57 36" src="https://github.com/user-attachments/assets/3ddec01e-47f4-4390-808c-c47126d4a0bf">

Parachain is being onboarded.

**Comment by hbulgarini** [comment]
Parachain has been onboarded and slots assigned.
