### ISSUE TITLE
[Parachain Onboarding | Slot Request] ParaId: 4023

### ISSUE THREAD

**Issue by asiniscalchi** [paseo-network/support#86]
### Parachain Name

LAOS Mercury

### ParaID

4023

### Parachain Manager Account

5C7cTzUE8vhQMzbKrRmsZqhGgk583JFENE7T73faqUVeYMdC

### Upload your Genesis State - Do not submit a compressed file.

[laos-mercury.genesis.state.txt](https://github.com/user-attachments/files/16456709/laos-mercury.genesis.state.txt)

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[laos-mercury.genesis.wasm.txt](https://github.com/user-attachments/files/16456711/laos-mercury.genesis.wasm.txt)

**Comment by hbulgarini** [comment]
Hello, as the demand of parachains in paseo is still acceptable and we can onboard more than one parachain per team for now, but please take into account that if the demand changes, this additional parachain assigned to the LAOS team will have to be offboarded to allow other teams to run their parachains in Paseo.

**Comment by al3mart** [comment]
Onboarding the parachain now. Slot assignation will follow

**Comment by al3mart** [comment]
Onboarded and building blocks

**Comment by asiniscalchi** [comment]
We kindly require to downgrade the parachain 4023 to parathread. We are willing to deregister the parathread and withdraw the deposit.
The network 4023 is bricked and we are going to create a new one leveraging coretime.

**Comment by educlerici-zondax** [comment]
following this in https://github.com/paseo-network/support/issues/112
