### ISSUE TITLE
[Parachain Onboarding | Slot Request] Energy Web X Paseo - ParaId: 3345

### ISSUE THREAD

**Issue by royki** [paseo-network/support#89]
### Parachain Name

Energy Web X Paseo

### ParaID

3345

### Parachain Manager Account

5HpSs5x9nvKzcDv1XeiVNmdUL9wWBhhiQN4DruDyA5ueJ155

### Upload your Genesis State - Do not submit a compressed file.

[pex-genesis-state.txt](https://github.com/user-attachments/files/16707739/pex-genesis-state.txt)

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[pex-genesis-wasm.txt](https://github.com/user-attachments/files/16707740/pex-genesis-wasm.txt)

**Comment by al3mart** [comment]
Onboarding the chain now. Will continue with lease assignment once the onboarding is done.
![image](https://github.com/user-attachments/assets/fd1e6139-ecb9-435c-a19e-e5f333c70318)
