### ISSUE TITLE
Reset the genesis state | ParaID: 4003

### ISSUE THREAD

**Issue by ganesh1997oli** [paseo-network/support#92]
We are running our node with paraID: `4003` but we are facing issue regarding producing blocks. We figure out that we need to reset the genesis state to make it produce block. Can you able to do that?

[para-4003-genesis-state.txt](https://github.com/user-attachments/files/16839601/para-4003-genesis-state.txt)
[para-4003-wasm.txt](https://github.com/user-attachments/files/16839602/para-4003-wasm.txt)

**Comment by educlerici-zondax** [comment]
@ganesh1997oli producing blocks again!
