### ISSUE TITLE
Reset Genesis State | Energy Web X Paseo - ParaID: 3345

### ISSUE THREAD

**Issue by royki** [paseo-network/support#95]
Can you please reset the Chain state. 

- **ParaID**: 3345
- **genesis-state** :  [pex-genesis-state-3345.txt](https://github.com/user-attachments/files/16874450/pex-genesis-state-3345.txt)
  - Checksum - `877525c35ba38cf988a9f1285b811732646e2a36ccea9f7c60bd640005c204c8`
- **genesis-wasm**:  [pex-genesis-wasm-3345.txt](https://github.com/user-attachments/files/16874452/pex-genesis-wasm-3345.txt)
  - Checksum - `125647c65725df040daa888bcbcf7a4fc211edd002a1286cd99996b96e8c0d96`

**Comment by hbulgarini** [comment]
Code and genesys updated with the files provided.

**Comment by royki** [comment]
> Code and genesys updated with the files provided.

Thanks @hbulgarini . Energy Web X Paseo started producing blocks. 😃 

By the way Do we need to do anything regarding the paraID lease ?
