### ISSUE TITLE
BUG - Coretime parachains downtime

### ISSUE THREAD

**Issue by al3mart** [paseo-network/support#96]
After enacting upgrade v1.3.1 some parachains weren't scheduled as expected.

**Comment by paradox-tt** [comment]
[coretime_dump_1.txt](https://github.com/user-attachments/files/17016459/coretime_dump_1.txt)

Log dump as requested.

**Comment by al3mart** [comment]
`2980622` re-execution.


[0xd589abdc5bc86ae230cb0f8f07123840cefdc9805ec4c529676ae44c3dc5e923.tar.gz](https://github.com/user-attachments/files/17017913/0xd589abdc5bc86ae230cb0f8f07123840cefdc9805ec4c529676ae44c3dc5e923.tar.gz)

**Comment by al3mart** [comment]
After much research we deemed that the migration was executed correctly.
A combination of enabling `EnableAssignmentsV2` and restarting the collators brought back the parachains to be scheduled as usual.
