### ISSUE TITLE
[Parachain Onboarding | Slot Request] ParaId: 4502

### ISSUE THREAD

**Issue by juangirini** [paseo-network/support#99]
### Parachain Name

Ideal Network

### ParaID

4502

### Parachain Manager Account

12ZHHNraSBqPNGsCgdynXNGi5GfVtZKCVZsV2gkZFwVACRDh

### Upload your Genesis State - Do not submit a compressed file.

[idn-4502-genesis-state.txt](https://github.com/user-attachments/files/17057932/idn-4502-genesis-state.txt)

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[idn-4502-wasm.txt](https://github.com/user-attachments/files/17057933/idn-4502-wasm.txt)

**Comment by juangirini** [comment]
UI PR https://github.com/polkadot-js/apps/pull/10934

**Comment by al3mart** [comment]
The provided manager account was funded to unlock the registration:
- https://paseo.subscan.io/extrinsic/3077654-2

**Comment by juangirini** [comment]
Thank you @al3mart, the parathread is now registered

**Comment by al3mart** [comment]
What is your plan regarding coretime ?
As we speak we are increasing the number of cores in Paseo, and coretime sales will start next week. Are you planning on procuring on demand, maybe?

Just asking to asses how much demand to expect and plan accordingly.

**Comment by juangirini** [comment]
on demand should work for us. We don't expect a huge demand, as we are just testing out a few things for now

**Comment by al3mart** [comment]
Alright, I'll close this issue for now then. Feel free to reach out if anything further is needed.
